# Generated by Django 4.1.4 on 2022-12-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employeeId", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("postalCode", models.CharField(max_length=25)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("activeInd", models.CharField(max_length=1)),
                ("addedDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["lastName", "firstName"],},
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["lastName", "firstName"], name="employeeMgm_lastNam_9ea556_idx"
            ),
        ),
    ]
