# Generated by Django 4.1.4 on 2022-12-26 03:19

from django.db import migrations, models
import django.db.models.deletion
import employeeMgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ("employeeMgmt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("desc", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("desc", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodStart", models.DateField(default="2023-01-01")),
                ("periodEnd", models.DateField(default="2023-01-05")),
                ("netPayment", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="Ww", max_length=10)),
                ("desc", models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(model_name="employee", name="activeInd",),
        migrations.RemoveField(model_name="employee", name="country",),
        migrations.RemoveField(model_name="employee", name="endDate",),
        migrations.RemoveField(model_name="employee", name="startDate",),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(default="M", max_length=1),
        ),
        migrations.AddField(
            model_name="employee",
            name="telephone",
            field=models.CharField(default=2322, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.CreateModel(
            name="WorkHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateWorked", models.DateField(default="2023-01-01")),
                ("startTime", models.TimeField(default="09:00")),
                ("endTime", models.TimeField(default="17:00")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("postalCode", models.CharField(max_length=25)),
                ("telephone", models.CharField(max_length=25)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateField(default="1900-01-01")),
                ("endDate", models.DateField(default="9999-12-31")),
                ("activeInd", models.CharField(default="Y", max_length=1)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.employee",
                    ),
                ),
                (
                    "jobTitle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.FloatField(default=0)),
                ("bonus", models.FloatField(max_length=50)),
                ("startDate", models.DateField(default="1900-01-01")),
                ("endDate", models.DateField(default="9999-12-31")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateField(default="1900-01-01")),
                ("endDate", models.DateField(default="9999-12-31")),
                ("activeInd", models.CharField(default="Y", max_length=1)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeMgmt.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employeeMgmt.office"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employeeMgmt.country"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=employeeMgmt.models.Department.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="employeeMgmt.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="jobTitle",
            field=models.ForeignKey(
                default=employeeMgmt.models.Job.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="employeeMgmt.job",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="jobType",
            field=models.ForeignKey(
                default=employeeMgmt.models.JobType.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="employeeMgmt.jobtype",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.ForeignKey(
                default=employeeMgmt.models.City.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="employeeMgmt.city",
            ),
        ),
    ]
