# Generated by Django 4.1.4 on 2022-12-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employeeMgmt",
            "0002_city_country_department_job_jobtype_salarypayment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="telephone",
            field=models.CharField(default="+223-12-34-56-78", max_length=25),
        ),
    ]
